### PR TITLE
Add gear_id to SummaryActivity and UpdatableActivity.

### PR DESCRIPTION
**Pull request by sshevlyagin**
gear_id was missing from the SummaryActivity and UpdatableActivity object. I'm adding it back and updating the example.

### CODE REVIEW

**Comment by mindy-stivers** [comment]
@sshevlyagin if you want to stub out the identifying data in your PR as harini mentioned, and then squash the commits, we can merge it to the live site.  Let us know if you have questions!

**Comment by sshevlyagin** [comment]
Thanks for the ping, I updated the pull request.

**Comment by mindy-stivers** [comment]
@sshevlyagin thanks, looks good! Could you squash your commits into one, too?

**Comment by sshevlyagin** [comment]
@mindy-stivers my last commit has all the changes in one, but i'm not sure how to get rid of the commit history on this pull request. Are we ok or is there something else I need to do?

**Comment by mindy-stivers** [comment]
@sshevlyagin You would need to do a rebase and squash to get the commits into one so we can merge them.  A couple of options...

Option 1 is to follow these instructions to clean up your commits:
1. `git rebase -i 8f02045` (squash commits)
1. `git rebase --continue` (it will say there is conflicts, probably as a result of the merge commits, but not really, --continue should take care of it)
1. (pull upstream master)
1. `git rebase -i upsteam/master`
1. (resolve conflicts, probably want to keep the upsteam gear id description)
1. `git add swagger/activity.json.mustache`
1. `git rebase --continue`

OR

Option 2 is to pull this branch where @yf6 has done all of the above, and make a new pull request: https://github.com/strava/developers.strava.com/tree/yf/sshevlyagin/gear_id

The downside of Option 2 is the commit appears to come from both of you, so you aren't getting solo attribution for the change.

**Pull request closed without merging**
