### PR TITLE
[API-627] Updated clubs responses

### PR DESCRIPTION
**Pull request by zackisaacs**

### CODE REVIEW

**Comment by hariniriyer** [comment]
Want to merge this? :)

**Comment by zackisaacs** [comment]
I'm waiting to merge and deploy until the active code is merged. And also until @MateoAO reviews. cough cough!

**Comment by MateoAO** [comment]
Sorry, been buried in ATD/MS related meetings. On the upside, ATD is already more successful than I ever imagined it would be in 2018. 

Any harm in launching this now? Worse case, people get data they'll stop getting very soon.

**Comment by zackisaacs** [comment]
Clear heads prevail. Merging now.

**Pull request merged**
